// Step1. import icons from FontAwesome library

import {
  faAddressCard,
  faAngleDown,
  faBars,
  faBatteryEmpty,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faBell,
  faBolt,
  faBug,
  faBullhorn,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faCloud,
  faCog,
  faEllipsisV,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faInfoCircle,
  faFilter,
  faFolder,
  faLink,
  faMoneyCheckAlt,
  faPlaneArrival,
  faPlus,
  faRegistered,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faStar,
  faSyncAlt,
  faTimes,
  faUser,
  faUsers,
  faUserGraduate
} from "@fortawesome/free-solid-svg-icons";

import {
  faClock,
  faEdit,
  faUserCircle,
  faSave,
  faImage,
  faTimesCircle,
  faTrashAlt
} from "@fortawesome/free-regular-svg-icons";

// Step 2. Add imported icons to variable (to use it inside project)

export const fontawesome_icons = {
  faAddressCard,
  faAngleDown,
  faBars,
  faBatteryEmpty,
  faBatteryQuarter,
  faBatteryHalf,
  faBatteryThreeQuarters,
  faBatteryFull,
  faBell,
  faBolt,
  faBug,
  faBullhorn,
  faCheckCircle,
  faChevronLeft,
  faChevronRight,
  faClock,
  faCloud,
  faCog,
  faEdit,
  faEllipsisV,
  faExclamationCircle,
  faEye,
  faEyeSlash,
  faFilter,
  faFolder,
  faInfoCircle,
  faImage,
  faLink,
  faMoneyCheckAlt,
  faPlaneArrival,
  faPlus,
  faRegistered,
  faSave,
  faSearch,
  faShoppingCart,
  faSignOutAlt,
  faSpinner,
  faStar,
  faSyncAlt,
  faTimes,
  faTimesCircle,
  faTrashAlt,
  faUser,
  faUserCircle,
  faUsers,
  faUserGraduate
};
